spring:
  application:
    name: gateway
  # 路由转发
  cloud:
    gateway:
      routes:
        - id: system #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
            #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: http://localhost:9001 #匹配后提供服务的路由地址
          predicates:
              - Path=/system/** #断言，路径相匹配的进行路由

server:
  servlet:
    context-path: /gateway
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

