spring:
  application:
    name: business
#  服务发布端口
server:
  port: 9002
  servlet:
    context-path: /business
# 配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
